### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by MaximeSoulie** [rlewkowicz/docker-mediawiki-stack#11]
URL : https://<LAN IP>/mw-config/index.php

When I click "Please set up the wiki first." I got an error

Output :
502 Bad Gateway

nginx/1.10.3

**Comment by rlewkowicz** [comment]
It's been a while since I played with this. If you visit the root url/ip for the wiki, it doesn't automatically take you to a set up page? Sounds like that's a partially set up wiki or something
