### ISSUE TITLE
can't edit wiki with VirtualEditor

### ISSUE THREAD

**Issue by crest55** [rlewkowicz/docker-mediawiki-stack#4]
I  set up the mediawiki stack use docker compose, and I configured my mediawiki successfully. But when I click 'Edit' tab to edit my wiki page, I hope the brower will open VirtualEditor, but a alter appeared, it said 

> "Error loading data from server: Could not connect to the server. Would you like to retry?". 

Then I checked my brower console, there was a error message:

> "https://restbase:7231/wiki/v1/page/html/Main_Page/10?redirect=false" net::ERR_NAME_NOT_RESOLVED 
RESTBase load failed: error

I want to ask how to solve the problem, anyone has idea? thanks.

**Comment by rlewkowicz** [comment]
@crest55 Sorry about the delay in response, which branch is this? I see the error there has restbase in it, master is unstable. You'll want to check out a branch (REL1_28 etc)

**Comment by rlewkowicz** [comment]
I'm confident the branches work properly. Please comment/reopen if you continue to have issues.

**Comment by crest55** [comment]
I checked out the branch REL1_28, and updated mwcore submodule. Then I deleted all the previous containers, and ran docker-compose up command.  When I clicked 'Edit' tab, I received the same alter message,  but it had another reason:

`Mixed Content: The page at 'https://192.168.1.9/Main_Page?action=edit&veswitched=1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://restbase:7231/wiki/v1/page/html/Main_Page?redirect=false'. This request has been blocked; the content must be served over HTTPS.`

Could you help me solve the problem?

**Comment by rlewkowicz** [comment]
@crest55 Looks like it's still trying to use restbase. In your LocalSettings.php file under  mwcore you I think you still have restbase. You could try replacing the $wgVirtualRestConfig portion under the parsoid section with this:

```
$wgVirtualRestConfig['modules']['parsoid'] = array(
  // URL to the Parsoid instance
  // Use port 8142 if you use the Debian package
  'url' => 'parsoid:8000',
  'domain' => 'wiki',
  'forwardCookies' => true
);
```

If you swapped uri's or domains you'll want to do that here aswell

**Comment by rlewkowicz** [comment]
The other cool thing about this platform is that you can hand it to me. You could zip up the folder and put it somewhere I can grab it and I can look at the exact same thing you're seeing.
