### ISSUE TITLE
Error when I run sudo ./runfirst.bash && \ command

### ISSUE THREAD

**Issue by evleite** [rlewkowicz/docker-mediawiki-stack#6]
Hi I am trying to run the mediawiki on docker but when I run the command sudo ./runfirst.bash && \
I got the follow problems:

user-MacBook-Pro:docker-mediawiki-stack user$ sudo ./runfirst.bash && \ dev
./runfirst.bash: line 9: service: command not found
./runfirst.bash: line 12: useradd: command not found
sed: 1: "/Development/images/doc ...": command i expects \ followed by text
chown: www-data.www-data: illegal user name

**Comment by rlewkowicz** [comment]
Ah yea, This is written for linux. I wanted to do one for mac, but this project on Mac is essentially unusable (Really to me docker on mac is unusable all together) given the way that Mac handles file system mounts:
https://github.com/docker/for-mac/issues/77
It's like Reeeeealy slow.

**Comment by rlewkowicz** [comment]
But I just realized, that you may have already worked around those limitations with some of the syncing plugins. 

rm -f $DIR/mediawiki/includes/installer/LocalSettingsGenerator.php
\cp $DIR/distribution-files/LocalSettingsGenerator.php $DIR/distribution-files/mwcore/mediawiki/includes/installer/LocalSettingsGenerator.php

Is mostly what you would need. I handle users across containers via the local passwd shadow and group files. I would have to go look again at how that is handled on mac. I was thinking about changing this to use a container just for user management, but then local host permissions can get weird.

**Comment by evleite** [comment]
Thank you very much for you help.

I was wondering if this can be handle by entry point file, what you think? This way the user and group will be set directly on container.

**Comment by evleite** [comment]
Another suggestion is to expose the extension folder on docker compose file, in order to upload extensions easily.

**Comment by rlewkowicz** [comment]
Currently the whole wiki is exposed under mwcore. All files that are needed to operate the wiki are fully exposed

**Comment by beckbg** [comment]
Checking in on this - thanks!

**Comment by rlewkowicz** [comment]
@beckg given the architecture differences between mac and linux and my time constraints I think I'm going to file this under will not fix (at least not personally. Some people have been forking and someone may put something together). Also https://github.com/docker/for-mac/issues/77 is a huge deal given the way my stuff is exposed. They have work arounds, but at this time docker for mac, in my opinion is absolutely not production ready. 

At some point I want to redo all this. A guy recommended basing it on laradock I'm not going to use that base, but I think I will emulate the way they do builds. Then it should just kinda work on mac by default.
