### ISSUE TITLE
Adding Extensions

### ISSUE THREAD

**Issue by calnation** [rlewkowicz/docker-mediawiki-stack#7]
Beautiful work that actually works! Thank you so much for the effort and sharing.

Pardon the n00b question, but regarding extensions, can you provide some guidance on the appropriate way to pre-install of them? Or do you think it's better to install them later after initial deployment? Thanks.

**Comment by rlewkowicz** [comment]
Usually better to add them afterwards. If you run into an extension that needs a particular php module baked in that my base image doesn't have let me know and I'll get it added ASAP
