### ISSUE TITLE
Build on top of Laradock

### ISSUE THREAD

**Issue by calnation** [rlewkowicz/docker-mediawiki-stack#8]
Not sure if you looked at it or not, but building on top of [Laradock](http://laradock.io/) can simplify the supporting this project (long-run) and also make the build more modular (more docker like).

On the side, I worked on making an additional Dockerfile based on the Jenkins file you have in core repo. I'll share it after I test it a bit, in case you're interested of course. My idea is to make the entire build more dynamic and portable and not depend much on version control. I know, extremism ;)

**Comment by rlewkowicz** [comment]
Sorry about the delay. I got a new job and moved halfway across the country XD. I definitely agree that something like that would make the project far more maintainable. It would allow you to contain everything you need for a project in just the docker files. I think that's how most of the professional world does it. I don't like that approach though. I use docker in a hybrid state. The services exist in the containers and that's it. I almost use it like a package manager. I don't like distributing build files. You can wrap it with things like chef and use the power of node attributes to deploy it to servers. Even with swarm/ceph I've architected a way to scale this out. 

The down side is though, is that collaboration and maintainability is much harder. I definitely could at least bring it into one repo, but now we still have the Jenkins builder and these semi obscure jobs (which are in jenkins files at least). The upshot however is kind of that wow factor. Run a few small commands, and bam you're up and running pretty darn quick. 

At some point I'll redo the whole thing. I just gotta get settled in.
